### ISSUE TITLE
Problem med  security group 'kubetest-ssh_access'

### ISSUE THREAD

**Issue by caleno** [UNINETT/research-lab#6]
Bruker Federation branch. 

Det virker som det blir blir problem når terraform skal opprette security group 'kubetest-ssh_access'.
Forsøker den å opprette den 2 eller flere ganger?? 

Stikk ord:  openstack_networking_secgroup_v2.grp_ssh_access
Slik ser den ut i min state fil. 

`                "openstack_networking_secgroup_v2.grp_ssh_access": {
                    "type": "openstack_networking_secgroup_v2",
                    "depends_on": [],
                    "primary": {
                        "id": "366a774d-01fd-4ffc-8e0e-fa594dc7f9b4",
                        "attributes": {
                            "description": "Security groups for allowing SSH access",
                            "id": "366a774d-01fd-4ffc-8e0e-fa594dc7f9b4",
                            "name": "kubetest-ssh_access",
                            "region": "osl",
                            "tenant_id": "e4f777d28d9f43b3907683892da06cf9"
                        },
`

## Logg

**First run**

Error applying plan:

4 error(s) occurred:

* module.masters.openstack_compute_instance_v2.master[0]: 1 error(s) occurred:

* openstack_compute_instance_v2.master.0: Error waiting for instance (9f8cdf88-ca44-491c-b19e-20571b7c4f51) to become ready: unexpected state 'ERROR', wanted target 'ACTIVE'. last error: %!s(<nil>)
* module.masters.openstack_compute_instance_v2.master[1]: 1 error(s) occurred:

* openstack_compute_instance_v2.master.1: Error waiting for instance (7db182a1-1f46-42c6-a020-37dcad104de9) to become ready: unexpected state 'ERROR', wanted target 'ACTIVE'. last error: %!s(<nil>)
* module.workers.openstack_compute_instance_v2.worker[2]: 1 error(s) occurred:

* openstack_compute_instance_v2.worker.2: Error waiting for instance (3df7890d-bd4d-420c-a7d5-4befbf8fe969) to become ready: unexpected state 'ERROR', wanted target 'ACTIVE'. last error: %!s(<nil>)
* module.securitygroups.openstack_networking_secgroup_rule_v2.rule_ssh_access_ipv4[0]: 1 error(s) occurred:

* openstack_networking_secgroup_rule_v2.rule_ssh_access_ipv4.0: Expected HTTP response code [201 202] when accessing [POST https://network.api.osl.uh-iaas.no:9696/v2.0/security-group-rules], but got 409 instead
{"NeutronError": {"message": "Security group rule already exists. Rule id is 2a22016f-62b3-469e-ab6b-5445b13fd522.", "type": "SecurityGroupRuleExists", "detail": ""}}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Second run**

Error applying plan:

4 error(s) occurred:

* module.securitygroups.openstack_networking_secgroup_rule_v2.rule_ssh_access_ipv4[0]: 1 error(s) occurred:

* openstack_networking_secgroup_rule_v2.rule_ssh_access_ipv4.0: Expected HTTP response code [201 202] when accessing [POST https://network.api.osl.uh-iaas.no:9696/v2.0/security-group-rules], but got 409 instead
{"NeutronError": {"message": "Security group rule already exists. Rule id is 2a22016f-62b3-469e-ab6b-5445b13fd522.", "type": "SecurityGroupRuleExists", "detail": ""}}
* module.masters.openstack_compute_instance_v2.master[1]: 1 error(s) occurred:

* openstack_compute_instance_v2.master.1: Error adding security group (kubetest-ssh_access) to OpenStack server (7db182a1-1f46-42c6-a020-37dcad104de9): Resource not found
* module.masters.openstack_compute_instance_v2.master[0]: 1 error(s) occurred:

* openstack_compute_instance_v2.master.0: Error adding security group (kubetest-ssh_access) to OpenStack server (9f8cdf88-ca44-491c-b19e-20571b7c4f51): Resource not found
* module.workers.openstack_compute_instance_v2.worker[2]: 1 error(s) occurred:

* openstack_compute_instance_v2.worker.2: Error adding security group (kubetest-ssh_access) to OpenStack server (3df7890d-bd4d-420c-a7d5-4befbf8fe969): Resource not found

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by gurvindersingh** [comment]
@knumor

**Comment by caleno** [comment]
Issue seems to have been resolved after the latest commit which I have merged. I'm not sure exactly what changes did the magic but the cluster is up an running 👍
